[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node app.js"
healthcheckPath = "/status"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[nixpacks]
nodejs-version = "16"
